kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "linuxbrew"
  namespace: "code-server"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "longhorn-retain-encrypt"
