= Goal
Run a Kubernetes Cluster on a (small) machine at home.

Run workloads like:

* Unify Control Center
* Homeassitent
* GitLab
* CodeServer

= Setup

* Fedora (35) as operating system
* k3s as Kubernetes distribution
* Longhorn for persistent storage
* Kubectl Bash Completion
* Starship
* 1Password Secrets Automation for storing secrets
* Traefik using LetsEncrypt

== k3s
https://rancher.com/docs/k3s/latest/en/[Documentation^]

----
curl -sfL https://get.k3s.io | sh -
----

== Longhorn
https://longhorn.io/docs/1.2.2/advanced-resources/os-distro-specific/csi-on-k3s/[Documentation^]

https://rancher.com/docs/k3s/latest/en/storage/[Install via kubectl^]:

----
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
----

== Kubectl Bash Completion
https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/

----
echo 'source <(kubectl completion bash)' >>~/.bashrc
echo 'alias k=kubectl' >>~/.bashrc
echo 'complete -F __start_kubectl k' >>~/.bashrc
----

== Starship
https://starship.rs/[Web Site]

Install:
----
sh -c "$(curl -fsSL https://starship.rs/install.sh)"
echo 'eval "$(starship init bash)"' >>~/.bashrc
----

== 1Password Secrets Automation
https://support.1password.com/connect-deploy-kubernetes[Setup^]
https://github.com/1Password/connect-helm-charts[Helm Repository^]
https://github.com/1Password/connect-helm-charts/tree/main/charts/connect[Details on the Connect Server and Operator^]
https://github.com/1Password/onepassword-operator[Operator]
https://github.com/1Password/onepassword-operator#usage[CRD Description]

https://helm.sh/docs/intro/install/#from-script[Install Helm^]

----
$ helm repo add 1password https://1password.github.io/connect-helm-charts
----

----
kubectl create namespace 1password
kns 1password
helm install connect 1password/connect --set-file connect.credentials=./1password-credentials.json --set operator.create=true --set operator.token.value=<token>
----

Create `OnePasswordItem` resources:
----
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: inst-ver2-eip-all-2-0-0-secrets
  namespace: 1password-test
spec:
  itemPath: "vaults/k8s/items/inst-ver2-eip-all-2-0-0-secrets"
----

----
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: test-password
  namespace: 1password-test
spec:
  itemPath: "vaults/k8s/items/test-password"
----

https://1password.community/discussion/125401/unable-to-get-item-from-vault[First problem encounterd^]

DNS issues:
----
k exec onepassword-connect-54c545fd75-qzs9v -c connect-sync -- bash -c 'openssl s_client -crlf -connect my.ent.1password.com:443 -servername my.ent.1password.com'
140261671187584:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:724:Temporary failure in name resolution
connect:errno=11
command terminated with exit code 1
----

Install dnsutils:

----
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: debug
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
----

----
kubectl exec -ti dnsutils -- cat /etc/resolv.conf
search debug.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.43.0.10
options ndots:5

kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
NAME                       READY   STATUS    RESTARTS   AGE
coredns-7448499f4d-jnkjr   1/1     Running   0          43h
[thofmann@w530 dns]$ kubectl logs --namespace=kube-system -l k8s-app=kube-dns
[ERROR] plugin/errors: 2 my.ent.1password.com. A: read udp 10.42.0.4:39985->8.8.4.4:53: i/o timeout
[ERROR] plugin/errors: 2 my.ent.1password.com. AAAA: read udp 10.42.0.4:42947->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 my.ent.1password.com. A: read udp 10.42.0.4:49874->8.8.4.4:53: i/o timeout
[ERROR] plugin/errors: 2 my.ent.1password.com. AAAA: read udp 10.42.0.4:56591->8.8.8.8:53: read: no route to host
[ERROR] plugin/errors: 2 my.ent.1password.com. A: read udp 10.42.0.4:49352->192.168.0.1:53: i/o timeout
[ERROR] plugin/errors: 2 my.ent.1password.com. AAAA: read udp 10.42.0.4:46497->8.8.4.4:53: read: no route to host
[ERROR] plugin/errors: 2 my.ent.1password.com. A: read udp 10.42.0.4:54904->8.8.4.4:53: i/o timeout
[ERROR] plugin/errors: 2 heise.de. A: read udp 10.42.0.4:52613->8.8.8.8:53: i/o timeout
[ERROR] plugin/errors: 2 www.heise.de. A: read udp 10.42.0.4:45065->192.168.0.1:53: i/o timeout
----

Solution / Workaround for Fedora /RHEL turn of firewalld

----
systemctl disable firewalld --now
----

After re-generating secrets using op CLI and updating the secrets access to vault is still forbidden.
Generating credentials at https://my.ent.1password.com/integrations/connect and using them both together finally worked:

----
kubectl create secret generic op-credentials --from-file=1password-credentials.json=op-session
kubectl create secret generic onepassword-token --from-literal=token=<token>
----

After actually adding a password to the item a secret with one entry is created:
----
k describe secret test-password
Name:         test-password
Namespace:    1password
Labels:       <none>
Annotations:  operator.1password.io/item-path: vaults/natvq4234uig7adkdn3ljcm74y/items/ijmwk25nocgm5ko346ydsf5uje
              operator.1password.io/item-version: 2

Type:  Opaque

Data
====
password:  24 bytes
----

A Secret Note item results in a secret with several entries:
----
k get secrets
NAME                              TYPE                                  DATA   AGE
default-token-6g6v7               kubernetes.io/service-account-token   3      3m22s
inst-ver2-eip-all-2-0-0-secrets   Opaque                                42     3m21s
test-password                     Opaque                                1      3m16s
----

== Traefik
https://doc.traefik.io/traefik/[Documentation^]
https://doc.traefik.io/traefik/https/acme/[Documentation on ACME^]
