env:
  TZ: "Europe/Berlin"
#  PLEX_UID: 0
#  PLEX_GID: 0
#hostNetwork: true

initContainers:
  volume-mount-hack:
    image: busybox
    command: ["sh", "-c", "ls -l /config"]
    #command: ["sh", "-c", "chown -R 200:200 /config/"]
    volumeMounts:
    - name: config
      mountPath: /config/

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: google-cloud-dns-cluster-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: plex.randombits.de
        http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
    tls:
      - hosts:
        - plex.randombits.de
        secretName: plex-cert

persistence:
  config:
    enabled: true
    size: 1Gi
    storageClass: longhorn-retain-encrypt
    accessMode: ReadWriteOnce
  transcode:
    enabled: true
    size: 5Gi
    type: emptyDir

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  # # Hardware acceleration using an Intel iGPU w/ QuickSync
  # # These IDs below should be matched to your `video` and `render` group on the host
  # # To obtain those IDs run the following grep statement on the host:
  # # $ cat /etc/group | grep "video\|render"
  # # video:x:44:
  # # render:x:109:
  supplementalGroups:
  - 39
  - 998
