#https://gitea.com/gitea/helm-chart/

gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: gitea@randombits.de
  config:
    server:
      DISABLE_SSH: true
    service:
      DISABLE_REGISTRATION: true
  podAnnotations:
    pre.hook.backup.velero.io/container: fsfreeze
    pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/data"]'
    post.hook.backup.velero.io/container: fsfreeze
    post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/data"]'      

image:
  rootless: true

ingress:
  enabled: true
  annotations: 
      cert-manager.io/cluster-issuer: google-cloud-dns-cluster-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
  hosts:
    - host: gitea.randombits.de
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
      - gitea.randombits.de
      secretName: gitea-cert

persistence:
  size: 20Gi
  storageClass: openebs-hostpath

postgresql:
  persistence:
    storageClass: openebs-hostpath
  primary:
    podAnnotations:
      pre.hook.backup.velero.io/container: fsfreeze
      pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/bitnami/postgresql"]'
      post.hook.backup.velero.io/container: fsfreeze
      post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/bitnami/postgresql"]'
#    size: 10Gi 
