#https://gitea.com/gitea/helm-chart/

gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: gitea@randombits.de
  config:
    server:
      DISABLE_SSH: true
    service:
      DISABLE_REGISTRATION: true

image:
  rootless: true

ingress:
  enabled: true
  annotations: 
      cert-manager.io/cluster-issuer: google-cloud-dns-cluster-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
  hosts:
    - host: gitea.randombits.de
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
      - gitea.randombits.de
      secretName: gitea-cert

persistence:
  size: 20Gi
  storageClass: longhorn-retain-encrypt

postgresql:
  persistence:
    storageClass: longhorn-retain-encrypt
#    size: 10Gi 
