env:
  PAPERLESS_REDIS: redis://paperless-redis-headless:6379
  PAPERLESS_OCR_LANGUAGE: deu
  PAPERLESS_OCR_MODE: skip_noarchive
  PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
  PAPERLESS_SECRET_KEY: "hsadsakjcsakjdshaiudsaiudsadkjsahdusahdusahud"
  PAPERLESS_ADMIN_USER:
    valueFrom:
      secretKeyRef:
        name: paperless
        key: admin-user
  PAPERLESS_ADMIN_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: paperless
        key: admin-password
  #PAPERLESS_ENABLE_HTTP_REMOTE_USER: true #SSO
  #PAPERLESS_LOGOUT_REDIRECT_URL
  PAPERLESS_CONSUMER_POLLING: 30
  PAPERLESS_CONSUMER_RECURSIVE: true
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true
  PAPERLESS_FILENAME_DATE_ORDER: YMD
  PAPERLESS_IGNORE_DATES: "16.06.1975, 02.12.1978"
  PAPERLESS_TIME_ZONE: "Europe/Berlin"
  TZ: "Europe/Berlin"

image:
  tag: 1.9.2

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: google-cloud-dns-cluster-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: paperless.randombits.de
        http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless
                port:
                  number: 8000
    tls:
      - hosts:
        - paperless.randombits.de
        secretName: paperless-cert

persistence:
  data:
    enabled: true
    size: 2Gi
    storageClass: openebs-hostpath
  media:
    enabled: true
    size: 20Gi
    storageClass: openebs-hostpath
  consume:
    enabled: true
    type: hostPath
    hostPath: /home/thofmann/scans
  export:
    enabled: true
    type: hostPath
    hostPath: /home/thofmann/paperless-export    

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  fullnameOverride: paperless-redis

initContainers:
  wait-for-redis:
    image: groundnuty/k8s-wait-for:v1.3
    args:
      - service
      - paperless-redis-headless      
