image:
  tag: "2021.12"

env:
  TZ: "Europe/Berlin"

# -- Set the resource requests / limits for the main container.
resources:
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
  #   memory: 800Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: http01-cluster-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/server-snippets: |
        location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        }
    hosts:
      - host: home-assistant.randombits.de
        http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
    tls:
      - hosts:
        - home-assistant.randombits.de
        secretName: home-assistant-cert

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: openebs-hostpath
  media:
    enabled: false
    type: hostPath
    hostPath: /mnt/tmhgdriveopus
    hostPathType: Directory
    mountPath: /music
    readOnly: true 

# -- Enable devices to be discoverable
hostNetwork: true

# -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
dnsPolicy: ClusterFirstWithHostNet
