apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: nameOfClusterIssuer
  name: echo
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.0
          imagePullPolicy: Always
          name: echo
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: http01-cluster-issuer
  name: echo
  namespace: echo
spec:
  rules:
    - host: echo.randombits.de
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echo
                port:
                  number: 80
  tls:
  - hosts:
    - echo.randombits.de
    secretName: echo-cert                    
