apiVersion: v1
kind: ConfigMap
metadata:
  name: error-pages
  namespace: ingress-nginx
data:
  error-page: |
    <!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>randombits</title>
            <style type="text/css">
              * {margin: 0; padding: 0}
              body {background: #000;}
              canvas {display: block;}
            </style>
        </head>
        <body>
          <canvas/>
          <script>
            // Initialising the canvas
            var canvas = document.querySelector('canvas'),
                ctx = canvas.getContext('2d');

            // Setting the width and height of the canvas
            canvas.width = window.innerWidth - 20;
            canvas.height = window.innerHeight - 20;

            // Setting up the letters
            var letters = '10';
            letters = letters.split('');

            // Setting up the columns
            var fontSize = 30,
                columns = canvas.width / fontSize;

            // Setting up the drops
            var drops = [];
            for (var i = 0; i < columns; i++) {
              drops[i] = 1;
            }

            // Setting up the draw function
            function draw() {
              ctx.fillStyle = 'rgba(0, 0, 0, .1)';
              ctx.fillRect(0, 0, canvas.width, canvas.height);
              for (var i = 0; i < drops.length; i++) {
                var text = letters[Math.floor(Math.random() * letters.length)];
                ctx.fillStyle = '#eeeeee';
                ctx.fillText(text, i * fontSize, drops[i] * fontSize);
                drops[i]++;
                if (drops[i] * fontSize > canvas.height && Math.random() > .95) {
                  drops[i] = 0;
                }
              }
            }

            // Loop the animation
            setInterval(draw, 90);
          </script>
        </body>
    </html>