env:
  TZ: "Europe/Berlin"

podAnnotations:
  pre.hook.backup.velero.io/container: fsfreeze
  pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/home"]'
  post.hook.backup.velero.io/container: fsfreeze
  post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/home"]'

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: google-cloud-dns-cluster-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: unifi.randombits.de
        http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi
                port:
                  number: 8443
                 
    tls:
      - hosts:
        - unifi.randombits.de
        secretName: unifi-cert

persistence:
  data:
    enabled: true
    size: 2Gi
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce

service:
  main:
    enabled: true
    #type: LoadBalancer
    ports:
      # -- Configure Web interface + API port
      # @default -- See values.yaml
      http:
        port: 8443
        protocol: HTTPS
  
  portal:
    enabled: true
    type: LoadBalancer
    ports:
      # -- Configure Captive Portal HTTP port
      # @default -- See values.yaml
      portal-http:
        enabled: true
        port: 8880
        protocol: HTTP
      # -- Configure Captive Portal HTTPS port
      # @default -- See values.yaml
      portal-https:
        enabled: true
        port: 8843
        protocol: HTTPS
      # -- Configure Speedtest port (used for UniFi mobile speed test)
      # @default -- See values.yaml
      speedtest:
        enabled: true
        port: 6789
        protocol: TCP

  tcp:
    enabled: true
    type: LoadBalancer
    ports:
      # -- Configure Controller port used for device command/control
      # @default -- See values.yaml
      controller:
        enabled: true
        port: 8080
        protocol: TCP

  udp:
    enabled: true
    type: LoadBalancer
    ports:
      # -- Configure STUN port
      # @default -- See values.yaml
      stun:
        enabled: true
        port: 3478
        protocol: UDP
      # -- Configure remote syslog port
      # @default -- See values.yaml
      syslog:
        enabled: true
        port: 5514
        protocol: UDP
      # -- Configure device discovery port
      # @default -- See values.yaml
      discovery:
        enabled: true
        port: 10001
        protocol: UDP       