apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: velero
  namespace: velero
spec:
  backupSyncPeriod: 2m0s
  provider: replicated.com/hostpath
  objectStorage:
    # This corresponds to a unique volume name
    bucket: velero
  config:
    # This path must exist on the host and be writable outside the group
    path: /mnt/disk-ext-1/velero
    # Must be provided if you're using Restic; [default mount] + [bucket] + [prefix] + "restic"
    resticRepoPrefix: /var/velero-local-volume-provider/velero/restic
