apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca-cluster
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-ca-cluster
  secretName: root-ca-cluster-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca-cluster-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-ca-cluster-secret
